### ISSUE TITLE
Could not find compartment with  name <nested-compartment-name>

### ISSUE THREAD

**Issue by sachin-pikle** [abhirockzz/fn-java-sdk-invoke#3]
Exception in thread "main" java.lang.Exception: Could not find compartment with  name <nested-comp-name> in tenancy ocid1.tenancy.oc1..aaaaaaaa6djoiiXXXXXXXXXXXXXXXXXXXXa
    at com.test.fn.FnInvokeExample.getCompartmentOCID(FnInvokeExample.java:205)
    at com.test.fn.FnInvokeExample.getAppOCID(FnInvokeExample.java:157)
    at com.test.fn.FnInvokeExample.invokeFunction(FnInvokeExample.java:97)
    at com.test.fn.MainClient.main(MainClient.java:34)

**Comment by sachin-pikle** [comment]
Please use one of the following solutions till we fix the issue:

a) Comment the code inside getCompartmentOCID() and return the compartment OCID

b) Use the following code in FnInvokeExample.java line #194 - "with compartmentIdInSubtree == true and AccessLevel==Accessible"

```
            ListCompartmentsRequest lcr = ListCompartmentsRequest.builder()
                    .compartmentId(tenantOCID)
                    .accessLevel(ListCompartmentsRequest.AccessLevel.Accessible)
                    .compartmentIdInSubtree(Boolean.TRUE)
                    .build();
```

**Comment by abhirockzz** [comment]
fixed by https://github.com/abhirockzz/fn-java-sdk-invoke/commit/500dafb265da6ced8453c60050cca672d36431b4
